language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
install:
  - sudo apt-get update
  - sudo apt-get install -qq libboost-dev
  - export CXX="g++-4.8" CC="gcc-4.8"
  - ${CXX} --version
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION nomkl numpy cython matplotlib scipy pytest
  - source activate test-environment
  - pip install falafel
  - make
  # workaround travis build issue (py.test import mismatch)
  # - python setup.py install
  - mkdir -p "$HOME/.config/matplotlib/"
  - 'echo "backend: Agg" > "$HOME/.config/matplotlib/matplotlibrc"'

script:
  - py.test -s --log
